name: detector_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - attrs==25.3.0
      - awkward==2.8.4
      - awkward-cpp==46
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cramjam==2.10.0
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.58.0
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - geomloss==0.2.6
      - greenlet==3.2.2
      - idna==3.10
      - importlib-metadata==8.7.0
      - jinja2==3.1.4
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - ml-lib==0.1.0
      - mpmath==1.3.0
      - multidict==6.4.4
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.0.0
      - pot==0.9.5
      - propcache==0.3.2
      - psutil==7.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - six==1.17.0
      - sqlalchemy==2.0.41
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - torch==2.7.0+cu118
      - torch-cluster==1.6.3+pt27cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt27cu118
      - torch-sparse==0.6.18+pt27cu118
      - torch-spline-conv==1.2.2+pt27cu118
      - torchaudio==2.7.0+cu118
      - torchvision==0.22.0+cu118
      - tqdm==4.67.1
      - triton==3.3.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uproot==5.6.2
      - urllib3==2.4.0
      - uuid7==0.1.0
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
